In [1]:
import array

In [5]:
x = array.array('b', [1,2,3])

In [4]:
x = array.array('b', [1,2,3.])

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
x + x

array('b', [1, 2, 3, 1, 2, 3])

In [6]:
import numpy as np

In [8]:
x = np.array([1, 2, 3.])

In [9]:
x

array([1., 2., 3.])

In [3]:
a= [1,2,3,4,5]
b= [4,5,6,7,8]

In [4]:
for x,y in zip(a,b):
    print(x*y)

4
10
18
28
40


In [7]:
a= np.array([1,2,3,4,5])
b= np.array([4,5,6,7,8])

In [8]:
a*b

array([ 4, 10, 18, 28, 40])

In [9]:
from functools import wraps

In [13]:
a = np.array([1,2,3])

In [14]:
a

array([1, 2, 3])

In [15]:
print(a)

[1 2 3]


In [11]:
import array

In [17]:
b = array.array('b', [1,2,3])

In [23]:
b

array('b', [1, 2, 3])

In [18]:
print(b)

array('b', [1, 2, 3])


In [19]:
class X:
    def __repr__(self):
        return 'repr'
    def __str__(self):
        return 'str'

In [20]:
x= X()

In [21]:
x

repr

In [22]:
print(x)

str


In [24]:
#dir, type, vars

type(a)

numpy.ndarray

In [25]:
type(b)

array.array

In [31]:
import tensorflow as tf

In [32]:
aa = tf.constant([1,2,3])

In [34]:
type(aa)

tensorflow.python.framework.ops.EagerTensor

In [33]:
tf.executing_eagerly() #컨스턴스가 eager 방식으로 만들어진다. 편의적인 기능.. 

True

In [29]:
np.ndarray((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [9.34609111e-307, 1.42413555e-306, 1.78019082e-306]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ScalarType

(int,
 float,
 complex,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.clongdouble,
 numpy.complex128,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.longdouble,
 numpy.int8,
 numpy.int16,
 numpy.intc,
 numpy.int32,
 numpy.int64,
 numpy.datetime64,
 numpy.timedelta64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uintc,
 numpy.uint32,
 numpy.uint64,
 numpy.void)

In [40]:
np.sctypes
#스칼라를 sc 라고 표현함

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [42]:
np.sctypeDict
#단축표현을 지원해준다.

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

In [43]:
a = np.array([[1,2,3], [4,5,6]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
b = np.array([[1,2,3], [4,5,]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [49]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
d = np.array([[1,2,3], [4,5,6]], dtype='i1')

In [56]:
d

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [51]:
#i1 은 int8 을 뜻한다..32비트 64비트가 기본이라서 아까는 안나왔던거다. 기본 외면 dtype이 나오는거다. 

In [58]:
f = np.array([[1,2,3], [4,5,6]], dtype=np.uint16)

In [59]:
f

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint16)

In [57]:
d.dtype

dtype('int8')

In [61]:
f.dtype

dtype('uint16')

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a.shape

(2, 3)

In [65]:
a.size

6

In [66]:
a.ndim

2

In [67]:
a.dtype

dtype('int32')

In [68]:
a.itemsize

4