In [1]:
import tensorflow as tf

In [2]:
(X_train,y_train),(X_test,y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [5]:
X_train[...,tf.newaxis].shape : channel last

(60000, 28, 28, 1)

In [7]:
X_train[:,tf.newaxis].shape : channel first

(60000, 1, 28, 28)

In [8]:
X_train = X_train.reshape(-1,28,28,1)

In [9]:
input_ = tf.keras.Input((28,28,1))

In [10]:
x = tf.keras.layers.Conv2D(32,3)(input_)

In [11]:
x = tf.keras.layers.MaxPool2D(2,2)(x)

In [12]:
x = tf.keras.layers.Flatten()(x)

In [13]:
x = tf.keras.layers.Dense(10)(x)

In [14]:
model = tf.keras.Model(input_,x)

In [15]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 5408)              0         
                                                                 
 dense (Dense)               (None, 10)                54090     
                                                                 
Total params: 54,410
Trainable params: 54,410
Non-trainable params: 0
_________________________________________________________

In [21]:
model(X_train[1][tf.newaxis])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[  2.956636, -86.1001  ,   8.818466,  19.055286,  31.524225,
         17.014097,  44.82248 ,  -8.7455  , -21.263063, -35.335728]],
      dtype=float32)>

In [22]:
tf.keras.utils.to_categorical(y_train)[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)