In [9]:
class A:
    __x = 1

    @property
    def tt(self):
        return 1

In [10]:
a = A()

In [11]:
a.tt()

TypeError: 'int' object is not callable

In [12]:
a.tt

1

In [13]:
import numpy as np

In [57]:
a = np.array([1,2,3,4])

In [58]:
a.shape

(4,)

In [51]:
class A:
    __x = 1

    @property
    def x(self):
        print('안알려줌')
        # return A.__x

    @x.setter
    def x(self, x):
        print('새롭게 값 할당 불가')
        # A.__x = x

In [52]:
a = A()

In [53]:
a.x

안알려줌


In [54]:
a.x = 2

새롭게 값 할당 불가


In [55]:
a.x

안알려줌


In [33]:
A.x #외부에서 __x에 접근할 경우

In [28]:
a.x #내부에서 __x에 접근할 경우

1

In [59]:
a.data

In [60]:
dir(a.data)

['__class__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'c_contiguous',
 'cast',
 'contiguous',
 'f_contiguous',
 'format',
 'hex',
 'itemsize',
 'nbytes',
 'ndim',
 'obj',
 'readonly',
 'release',
 'shape',
 'strides',
 'suboffsets',
 'tobytes',
 'tolist',
 'toreadonly']

In [70]:
a = np.arange(24).reshape(4,2,3)

In [81]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [72]:
a.shape

(4, 2, 3)

In [77]:
a.dtype

dtype('int32')

In [73]:
import tensorflow as tf

In [76]:
(X_train,y_train),(X_text,y_test) = tf.keras.datasets.mnist.load_data()

In [78]:
import pprint

In [83]:
from pprint import pprint

In [79]:
dir(pprint)

['PrettyPrinter',
 '_StringIO',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_builtin_scalars',
 '_collections',
 '_dataclasses',
 '_perfcheck',
 '_recursion',
 '_safe_key',
 '_safe_tuple',
 '_sys',
 '_types',
 '_wrap_bytes_repr',
 'isreadable',
 'isrecursive',
 'pformat',
 'pp',
 'pprint',
 're',
 'saferepr']

In [84]:
pprint(a)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])


In [90]:
np.add

<ufunc 'add'>

In [89]:
np.add([1,2], [4,5])

array([5, 7])

In [91]:
from operator import add

In [92]:
add([1,2], [4,5])

[1, 2, 4, 5]

In [93]:
add

<function _operator.add(a, b, /)>

In [94]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [95]:
a*b

array([1, 4, 9])

In [96]:
a@b #1,4,9 더한 값이다. inner product 내적 이라고 한다... 수학에서...

14

In [97]:
np.dot(a,b)

14

In [98]:
a.dot(b)

14

In [99]:
# 왜 같을까? a.dot(b)가 존재하면 function 이 존재할 수 있으니까. np.dot(a,b) 이 존재하는거다. 
# 함수형 패러다임 잘 쓰려면 , 함수 잘 써야하고, 함수의 존재를 잘 알아야 한다.

In [101]:
aa = np.array([[1,2,],[4,5,]])
bb = np.array([[1,2,],[4,5,]])

In [102]:
aa*bb

array([[ 1,  4],
       [16, 25]])

In [103]:
aa@bb

array([[ 9, 12],
       [24, 33]])

In [104]:
a=np.array([1,2,3,4])
bb=np.array([1,2,3,])

In [105]:
a+bb

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [106]:
a

array([1, 2, 3, 4])

In [107]:
a+1

array([2, 3, 4, 5])

In [108]:
a>2

array([False, False,  True,  True])

In [109]:
c = [1,2,3]

In [110]:
d = c

In [111]:
d[0] =100

In [112]:
c

[100, 2, 3]

In [113]:
id(c)

1440728096320

In [114]:
id(d)

1440728096320

In [115]:
c = [1,2,3]
d = c
d[0] = 100

In [116]:
e=[1,2,3]
f = e[:]
f[0] = 100

In [117]:
e

[1, 2, 3]

In [118]:
id(e)

1440727331520

In [119]:
id(f)

1440728341312

In [123]:
cc = [[1,2], [3,4]]
dd = cc
dd[0][0] = 100

In [124]:
cc

[[100, 2], [3, 4]]

In [130]:
cc = [[1,2], [3,4]]
dd = cc[:]
dd[0][0] = 100

In [131]:
cc

[[100, 2], [3, 4]]

In [133]:
import copy

In [134]:
cc = [[1,2], [3,4]]
dd = copy.deepcopy(cc)
dd[0][0] = 100

In [135]:
cc

[[1, 2], [3, 4]]

In [136]:
...

Ellipsis

In [137]:
type(...)

ellipsis

In [138]:
dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']