In [1]:
from sklearn.linear_model import Perceptron

## logistic regression - 중요한 개념을 알아보자

In [2]:
import seaborn as sns

In [3]:
iris = sns.load_dataset('iris')

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
lr = LogisticRegression()
# solver : {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'},    
#  - For small datasets, 'liblinear' is a good choice, whereas 'sag'
          # and 'saga' are faster for large ones;

In [7]:
lr.fit(iris.iloc[:, :-1], iris.species)

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [8]:
lr = LogisticRegression(solver='liblinear')

In [9]:
lr.fit(iris.iloc[:, :-1], iris.species)

LogisticRegression(solver='liblinear')

In [10]:
lr.predict([[2,3,3,3]])

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['virginica'], dtype=object)

In [11]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier

In [13]:
ovo = OneVsOneClassifier(LogisticRegression())
#이것도 하이퍼 파라미터다... 

In [14]:
from sklearn.neural_network import MLPClassifier
#사이킷런에서도 딥러닝 할 수 있으나.. 초딩 수준의 적은 용도라고 한다.

In [15]:
import tensorflow as tf

In [16]:
from sklearn.datasets import load_iris

In [17]:
data = load_iris()

In [18]:
#잊지말자. 우리 아직 오버피팅 중이다. 
# 문제 정의 : 아이리시 꽃 3종류를 분류하자.
# 데이터 150여개 뿐이니까 간단한 모델 쓰는게 좋다.
# 가장 간단한 모델이 뭐다? 리니어 모델이다.
# 로지스틱 모델은 시그모이드 함수 때문에 굉장히 성능 좋은 함수이고, 이런 저질 예시에는 안쓴다.

In [19]:
# 딥러닝 쓰면 좋은점? 내가 구조를 만들수 있다. 
# 어떻게?
# 알고리드믹 모델링
# 성능을 내가 조절할 수 있다.

In [21]:
input_ = tf.keras.Input((4,))
# 왜 tuple 형태로 넣을까? 비정형데이터는 2,3,4차도 들어갈수있거든. 이건 convolution 할 때 얘기해줄 예정. 

In [23]:
x = tf.keras.layers.Dense(16)

In [24]:
# callable 3가지 : class, function, __call__
dir(x)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_auto_config',
 '_auto_get_config',
 '_auto_track_sub_layers',
 '_autocast',
 '_autographed_call',
 '_build_input_shape',
 '_call_spec',
 '_callable_losses',
 '_captured_weight_regularizer',
 '_cast_single_input',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_compute_dtype',
 '_compute_dtype_object',
 '_dedup_weights',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialization_dependencies',
 '_deserialize_from_proto',
 '_dt

In [25]:
x = tf.keras.layers.Dense(16)(input_)
#input_ 을 16개의 퍼셉트론에 넣어보겠다는 뜻이다.

In [26]:
#맨 마지막 레이어는 결과값에 맞춘다. 
# 아이리시는 3개로.

In [27]:
x = tf.keras.layers.Dense(3)(x)

In [28]:
output = tf.keras.layers.Dense(3)(x)

In [29]:
model = tf.keras.models.Model(input_, output)

In [30]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_1 (Dense)             (None, 16)                80        
                                                                 
 dense_2 (Dense)             (None, 3)                 51        
                                                                 
 dense_3 (Dense)             (None, 3)                 12        
                                                                 
Total params: 143 (572.00 Byte)
Trainable params: 143 (572.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
dd = data.data[:3]

In [33]:
model
#얘도 합성함수다. 그러니 데이터 집어넣을 수 있다!

In [37]:
model(dd)
#왜 3개이게? one-hot encoding 이라서. 
# 100
# 010
# 001
# 이걸 학습시켜서 원하는 결과 나오게 하는게 뉴럴 네트워크.

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-3.2149594,  1.1627604, -2.5513968],
       [-2.9973588,  1.0139813, -2.4130452],
       [-2.9588823,  1.0619897, -2.3525293]], dtype=float32)>

In [38]:
# Dense 는 퍼셉트론이다. activation function 을 넣어보겠다.

In [39]:
input_ = tf.keras.Input((4,))
x = tf.keras.layers.Dense(16)(input_)

x = tf.keras.activations.relu(x)
# x = tf.keras.activations.sigmoid(x)
# x = tf.keras.activations.tanh(x)
# x = tf.keras.activations.(x)

output = tf.keras.layers.Dense(3)(x)

In [40]:
model.summary()
#output shape 에 None 이라는건 정해지지 않았다는거다. 
#행렬 곱 특성 때문. 

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_1 (Dense)             (None, 16)                80        
                                                                 
 dense_2 (Dense)             (None, 3)                 51        
                                                                 
 dense_3 (Dense)             (None, 3)                 12        
                                                                 
Total params: 143 (572.00 Byte)
Trainable params: 143 (572.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [43]:
model.weights
# model.weights[0]
#array 로 볼수있는거다. 
# 4 *16....  이 부분이 이해가 안감.....ㅜ,

[<tf.Variable 'dense_1/kernel:0' shape=(4, 16) dtype=float32, numpy=
 array([[ 0.03472668,  0.27148277,  0.45407498,  0.2120831 ,  0.41434288,
          0.28940755, -0.4477024 ,  0.07412654,  0.48387122,  0.00276947,
         -0.09593514, -0.14797714, -0.12518966, -0.3144691 , -0.499936  ,
          0.3371424 ],
        [-0.17171293, -0.20714936,  0.48371077, -0.03658348,  0.40479404,
         -0.47678015, -0.14856726,  0.5203937 , -0.40104437,  0.16994208,
          0.13442326,  0.26124984,  0.02142334, -0.39139384, -0.38384956,
          0.12959659],
        [ 0.4927559 ,  0.03826886,  0.46201134, -0.35392302,  0.17141062,
          0.49438775, -0.5388891 ,  0.29630232, -0.4423861 , -0.3883287 ,
         -0.06313553, -0.22174183, -0.2809075 , -0.24369693,  0.3313855 ,
         -0.44596797],
        [-0.10843572,  0.36846054,  0.16847855,  0.3708914 , -0.54754853,
          0.00839561,  0.50398755,  0.2945937 , -0.20574018,  0.29179615,
          0.03328997,  0.06296968, -0.26667193, 

In [44]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
#원핫인코딩으로 바꿔주면
tf.keras.utils.to_categorical(data.target)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0