In [1]:
from sklearn.datasets import load_wine

In [6]:
data = load_wine(as_frame=True)

In [7]:
wine = data.frame

In [4]:
!pip install -U ydata-profiling
# 근데 우리보고 쓰지말라고 함... 

^C


In [5]:
!pip install -U pandas-profiling

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/324.4 kB ? eta -:--:--
     ---------------- --------------------- 143.4/324.4 kB 4.3 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ----------------------------- -------- 256.0/324.4 kB 3.2 MB/s eta 0:00:01
     ------------------------------ ----- 276.5/324.4 kB 741.6 kB/s eta 0:00:01
     ------------------------------- ---- 286.7/324.4 kB 681.0 kB/s eta 0:00:01
     -----------------------------------  317.4/324.4 kB 678.1 kB/s eta 0:00:01
     ------------------------------------ 324.4/3

In [9]:
!pip install -U typing-extensions

Defaulting to user installation because normal site-packages is not writeable


In [13]:
from functools import partial

In [12]:
wine.head(10)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   
7    14.06        2.15  2.61               17.6      121.0           2.60   
8    14.83        1.64  2.17               14.0       97.0           2.80   
9    13.86        1.35  2.27               16.0       98.0           2.98   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0  
5                          2.85   1450.0       0  
6                          3.58   1290.0       0  
7                          3.58   1295.0       0  
8                          2.85   1045.0       0  
9                          3.55   1045.0       0

In [14]:
wine.head1 = partial(wine.head, n=10)

In [15]:
wine.head1()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   
7    14.06        2.15  2.61               17.6      121.0           2.60   
8    14.83        1.64  2.17               14.0       97.0           2.80   
9    13.86        1.35  2.27               16.0       98.0           2.98   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0  
5                          2.85   1450.0       0  
6                          3.58   1290.0       0  
7                          3.58   1295.0       0  
8                          2.85   1045.0       0  
9                          3.55   1045.0       0

## bagging 써보기

In [16]:
from sklearn.ensemble import BaggingClassifier

In [48]:
bc = BaggingClassifier()
#estimator=None,이라고 되어있는데. 사이킷런에서 이러하면, 
# estimator : object, default=None
#     The base estimator to fit on random subsets of the dataset.
#     If None, then the base estimator is a
#     :class:`~sklearn.tree.DecisionTreeClassifier`.

In [18]:
vars(bc)
#학습 전

{'estimator': None,
 'n_estimators': 10,
 'estimator_params': (),
 'base_estimator': 'deprecated',
 'max_samples': 1.0,
 'max_features': 1.0,
 'bootstrap': True,
 'bootstrap_features': False,
 'oob_score': False,
 'warm_start': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0}

In [19]:
#estimator 에 집어넣어보기
bc.fit(wine.iloc[:,:-1], wine.target)


BaggingClassifier()

In [21]:
vars(bc)
#학습 후

{'estimator': None,
 'n_estimators': 10,
 'estimator_params': (),
 'base_estimator': 'deprecated',
 'max_samples': 1.0,
 'max_features': 1.0,
 'bootstrap': True,
 'bootstrap_features': False,
 'oob_score': False,
 'warm_start': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0,
 'feature_names_in_': array(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
        'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
        'proanthocyanins', 'color_intensity', 'hue',
        'od280/od315_of_diluted_wines', 'proline'], dtype=object),
 'n_features_in_': 13,
 '_n_samples': 178,
 'classes_': array([0, 1, 2]),
 'n_classes_': 3,
 'estimator_': DecisionTreeClassifier(),
 '_max_samples': 178,
 '_max_features': 13,
 'estimators_': [DecisionTreeClassifier(random_state=365624370),
  DecisionTreeClassifier(random_state=21895217),
  DecisionTreeClassifier(random_state=1381947436),
  DecisionTreeClassifier(random_state=416794338),
  DecisionTreeClassifier(random_state=15

In [22]:
#cross validation
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(wine.iloc[:,:-1], wine.target)

In [24]:
bc.fit(X_train,y_train)

BaggingClassifier()

In [25]:
#예측할 때 어떻게 나오나
bc.predict(X_test)

array([2, 0, 2, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 2, 1, 2,
       1, 2, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0,
       1])

In [26]:
bc.base_estimator

'deprecated'

In [27]:
bc.base_estimator_

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute `base_estimator_` was deprecated in version 1.2 and will be removed in 1.4. Use `estimator_` instead.
  warnings.warn(msg, category=FutureWarning)


DecisionTreeClassifier()

In [28]:
bc.bootstrap
#부트스트랩 사용했다.

True

In [30]:
dir(bc)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_estimator_type',
 '_fit',
 '_get_default_requests',
 '_get_estimators_indices',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_make_estimator',
 '_max_features',
 '_max_samples',
 '_more_tags',
 '_n_samples',
 '_parallel_args',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_seeds',
 '_set_oob_score',
 '_val

In [29]:
bc.bootstrap_features

False

In [34]:
bc.predict(X_test)

array([2, 0, 2, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 2, 1, 2,
       1, 2, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0,
       1])

In [33]:
bc.predict_proba(X_test)
#확률로 계산해준다.
# [0.4, 0.1, 0.5] 확률개념으로 예측해줬다는거...

# 사이킷런은 두개가 같을 때 대표적으로 앞에 있는걸로 확률을 해준다. 
# 그러니 결국 predict 와 predict_proba 를 같이 보는게 좋다.

array([[0.4, 0.1, 0.5],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0.8, 0.1, 0.1],
       [0.6, 0.4, 0. ],
       [0.1, 0.9, 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.1, 0.9, 0. ],
       [0. , 1. , 0. ],
       [0.1, 0.2, 0.7],
       [0. , 1. , 0. ],
       [0.2, 0.8, 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.1, 0.9],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.9, 0.1, 0. ],
       [0.2, 0.1, 0.7],
       [0. , 0.9, 0.1],
       [0. , 0.3, 0.7],
       [0. , 1. , 0. ],
       [0.2, 0.2, 0.6],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0.1, 0.2, 0.7],
       [0. , 0.1, 0.9],
       [0.9, 0.1, 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.5, 0.5, 0. ],
       [0.1, 0.2, 0.7],
       [0. , 0. , 1. ],
       [0.9, 0. 

In [35]:
#머신러닝에서 격차를 줄이는 방법. 
# 로그를 씌우면 된다.. or 루트를 씌운다.
# 값의 범위가 클 때 값의 범위를 줄일때..ㅠㅠ
bc.predict_log_proba(X_test)
#log 0 은 마이너스 무한대가 된다함..

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)
C:\Users\u

array([[-9.16290732e-01, -2.30258509e+00, -6.93147181e-01],
       [-4.44089210e-16,            -inf,            -inf],
       [           -inf,            -inf, -4.44089210e-16],
       [-2.23143551e-01, -2.30258509e+00, -2.30258509e+00],
       [-5.10825624e-01, -9.16290732e-01,            -inf],
       [-2.30258509e+00, -1.05360516e-01,            -inf],
       [-4.44089210e-16,            -inf,            -inf],
       [-4.44089210e-16,            -inf,            -inf],
       [-2.30258509e+00, -1.05360516e-01,            -inf],
       [           -inf, -4.44089210e-16,            -inf],
       [-2.30258509e+00, -1.60943791e+00, -3.56674944e-01],
       [           -inf, -4.44089210e-16,            -inf],
       [-1.60943791e+00, -2.23143551e-01,            -inf],
       [           -inf, -4.44089210e-16,            -inf],
       [           -inf, -4.44089210e-16,            -inf],
       [           -inf, -2.30258509e+00, -1.05360516e-01],
       [-4.44089210e-16,            -inf

## KNN 알고리즘을 써보기

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
bc = BaggingClassifier(KNeighborsClassifier())

In [38]:
vars(bc)
# 'estimator': KNeighborsClassifier(), 로 나온다.

{'estimator': KNeighborsClassifier(),
 'n_estimators': 10,
 'estimator_params': (),
 'base_estimator': 'deprecated',
 'max_samples': 1.0,
 'max_features': 1.0,
 'bootstrap': True,
 'bootstrap_features': False,
 'oob_score': False,
 'warm_start': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0}

In [39]:
X_train, X_test, y_train, y_test = train_test_split(wine.iloc[:,:-1], wine.target)

In [40]:
bc.fit(X_train,y_train)

BaggingClassifier(estimator=KNeighborsClassifier())

In [41]:
bc.predict(X_test)

array([0, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 2, 1, 2, 0, 0, 0, 1,
       1, 1, 0, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 1, 1, 1, 0,
       1])

In [42]:
bc.predict_proba(X_test)
#원래 확률 개념이 없지만, 자기들만의 확률 계산을 해준다. 

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.5 ],
       [0.  , 0.84, 0.16],
       [0.  , 0.22, 0.78],
       [0.  , 0.56, 0.44],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.66, 0.34, 0.  ],
       [0.  , 0.78, 0.22],
       [0.  , 0.92, 0.08],
       [0.5 , 0.18, 0.32],
       [0.  , 0.86, 0.14],
       [0.  , 0.74, 0.26],
       [0.  , 0.92, 0.08],
       [1.  , 0.  , 0.  ],
       [0.36, 0.18, 0.46],
       [0.24, 0.48, 0.28],
       [0.44, 0.1 , 0.46],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.78, 0.22],
       [0.  , 0.96, 0.04],
       [0.08, 0.66, 0.26],
       [1.  , 0.  , 0.  ],
       [0.36, 0.16, 0.48],
       [1.  , 0.  , 0.  ],
       [0.22, 0.62, 0.16],
       [0.3 , 0.3 , 0.4 ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.64, 0.36],
       [0.  , 0.4 , 0.6 ],
       [1.  , 0.  , 0.  ],
       [0.58, 0.38, 0.04],
       [0.  , 0.54, 0.46],
       [0.  , 0.98, 0.02],
       [0.54, 0.18, 0.28],
 

In [43]:
bc.predict_log_proba(X_test)

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\ensemble\_bagging.py:934: RuntimeWarning: divide by zero encountered in log
  log_proba = np.log(self.predict_proba(X))


array([[ 0.        ,        -inf,        -inf],
       [       -inf, -0.69314718, -0.69314718],
       [       -inf, -0.17435339, -1.83258146],
       [       -inf, -1.51412773, -0.24846136],
       [       -inf, -0.5798185 , -0.82098055],
       [       -inf,  0.        ,        -inf],
       [ 0.        ,        -inf,        -inf],
       [-0.41551544, -1.07880966,        -inf],
       [       -inf, -0.24846136, -1.51412773],
       [       -inf, -0.08338161, -2.52572864],
       [-0.69314718, -1.71479843, -1.13943428],
       [       -inf, -0.15082289, -1.96611286],
       [       -inf, -0.30110509, -1.34707365],
       [       -inf, -0.08338161, -2.52572864],
       [ 0.        ,        -inf,        -inf],
       [-1.02165125, -1.71479843, -0.77652879],
       [-1.42711636, -0.73396918, -1.27296568],
       [-0.82098055, -2.30258509, -0.77652879],
       [ 0.        ,        -inf,        -inf],
       [ 0.        ,        -inf,        -inf],
       [ 0.        ,        -inf,       

In [44]:
bc.decision_function()
#있는애가 있고, 없는애가 있다고 함.

AttributeError: This 'BaggingClassifier' has no attribute 'decision_function'

In [45]:
knn = KNeighborsClassifier()

In [46]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [47]:
knn.decision_function

AttributeError: 'KNeighborsClassifier' object has no attribute 'decision_function'

In [ ]:
#knn 집어넣었을때는 decision function 이 없다. 

In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
dt = DecisionTreeClassifier()

In [51]:
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [52]:
dt.decision_path(X_test).toarray()

array([[1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0,

In [54]:
bc.decision_function(X_test)

AttributeError: This 'BaggingClassifier' has no attribute 'decision_function'

## logistic regression 알고리즘 써보기

In [55]:
from sklearn.linear_model import LogisticRegression

In [60]:
bc.fit(X_train,y_train)

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mode

BaggingClassifier(estimator=LogisticRegression())

In [61]:
bc.decision_function(X_test)

array([[ 6.29497822, -3.4162226 , -2.87875562],
       [-1.39812923,  4.22747978, -2.82935055],
       [-0.85043925,  4.79265364, -3.94221438],
       [-2.69678902, -7.82373758, 10.5205266 ],
       [-3.69686317, -5.11856656,  8.81542974],
       [-3.99579977,  5.55309146, -1.5572917 ],
       [ 5.5666752 , -3.84765111, -1.7190241 ],
       [ 2.78664155,  0.76248737, -3.54912892],
       [-2.37615783,  6.26745938, -3.89130155],
       [-1.5504446 ,  5.68152985, -4.13108524],
       [ 2.22033529,  2.04885627, -4.26919156],
       [-2.82311226,  3.8481737 , -1.02506144],
       [-2.93337956,  4.95273925, -2.01935968],
       [-2.14233828,  0.34373503,  1.79860325],
       [10.68729146, -7.9496947 , -2.73759676],
       [ 1.28585614, -7.5482895 ,  6.26243336],
       [ 0.77670294,  1.25593886, -2.0326418 ],
       [-0.59904255, -2.26168729,  2.86072985],
       [ 6.9539106 , -3.55146259, -3.402448  ],
       [ 7.07657295, -2.47260386, -4.6039691 ],
       [ 4.38245847, -3.20146558, -1.180

In [ ]:
#vars 확인 꼭 하고. 점 눌러서 이 기능 있는지 없는지 확인해봐야한다. 
# 모든 프레임워크들마다 특징이 있다. 
# 할때마다 익혀야한다. 
# 기계학습은 사이킷런을 기준으로 생각하면된다함...

## Voting classifier

In [62]:
from sklearn.ensemble import VotingClassifier

In [63]:
knn = KNeighborsClassifier()
lr = LogisticRegression()
dt = DecisionTreeClassifier()

In [64]:
vc = VotingClassifier([('knn', knn),('lr', lr),('dt', dt)])
# estimators, 여러개 넣어라는거. list of tuple 방식. => 하이퍼 파라미터 튜닝에 유용하다.

In [65]:
#voting <- 다수결. 방식을 보겠다. 

In [66]:
# 정확한 애한테 가중치를 준다. 어떻게 weight 주는가가 중요하다. 하이퍼 파라미터로 웨이트 주는거 정말 어렵다.

# stacking

In [67]:
from sklearn.ensemble import StackingClassifier

In [69]:
sc = StackingClassifier([('knn', KNeighborsClassifier()),('dt', DecisionTreeClassifier())])
# estimators : list of (str, estimator)  = list of tuple

# 딥러닝은 logistic Regression 
# 그래서 얘네도 knn, dt 학습시키고 lr 에 넣으면 학습 끝이라고 한다.

In [70]:
sc.fit(X_train, y_train)

StackingClassifier(estimators=[('knn', KNeighborsClassifier()),
                               ('dt', DecisionTreeClassifier())])

In [71]:
#다다음주부터 텐서플로우, 파이토치로 딥러닝 배울거다... 그 때 다시 말할건데 기억해라^^